// Generated by Haxe 4.0.3
(function ($hx_exports, $global) { "use strict";
var MnDialog = $hx_exports["MnDialog"] = function(width,height,id,cssPrefix) {
	if(height == null) {
		height = 20;
	}
	if(width == null) {
		width = 250;
	}
	this.bDragging = false;
	this.bTouchAvailable = false;
	this.maxBodyHeight = 400;
	this.id = "";
	this.colorBase = "#eeeeff";
	this.colorButton = "#6666ff";
	this.colorTitleText = "#ffffff";
	this.colorTitle = "#9999ff";
	this.keyupEnabled = false;
	this.btFocused = "none";
	this.btLang = "en";
	this.btType = "OK";
	var _gthis = this;
	if(id != null) {
		this.id = id;
	}
	if(cssPrefix != null) {
		this.cssPrefix = cssPrefix;
	} else {
		this.cssPrefix = "mndlg_" + new Date().getTime();
	}
	this.width = width;
	this.height = height;
	this.outputCSS(false);
	cssPrefix = this.cssPrefix + "_";
	this.divBG = window.document.createElement("div");
	this.divBG.className = cssPrefix + "bg";
	window.document.body.appendChild(this.divBG);
	this.divBase = window.document.createElement("div");
	this.divBase.className = cssPrefix + "base";
	if(this.id != "") {
		this.divBase.id = this.id;
	}
	this.divBG.appendChild(this.divBase);
	this.divTitle = window.document.createElement("div");
	this.divTitle.className = cssPrefix + "title";
	this.divTitle.textContent = "Title";
	this.divBase.appendChild(this.divTitle);
	this.divBody = window.document.createElement("div");
	this.divBody.textContent = "Body";
	this.divBody.className = cssPrefix + "body";
	this.divBase.appendChild(this.divBody);
	this.divButtons = window.document.createElement("div");
	this.divButtons.className = cssPrefix + "buttons";
	this.divBase.appendChild(this.divButtons);
	this.button1 = window.document.createElement("button");
	this.button1.textContent = "OK";
	this.button1.value = "OK";
	this.button1.className = cssPrefix + "button";
	this.button1.name = "button1";
	this.divButtons.appendChild(this.button1);
	this.button2 = window.document.createElement("button");
	this.button2.textContent = "Cancel";
	this.button2.value = "Cancel";
	this.button2.className = cssPrefix + "button";
	this.button2.name = "button2";
	this.divButtons.appendChild(this.button2);
	this.button3 = window.document.createElement("button");
	this.button3.textContent = "NO!";
	this.button3.value = "No";
	this.button3.className = cssPrefix + "button";
	this.button3.name = "button3";
	this.divButtons.appendChild(this.button3);
	this.setButtonType(this.btType,this.btLang);
	var evPress = "click";
	var evDragStart = "mousedown";
	var evDragMove = "mousemove";
	var evDragEnd = "mouseup";
	if(Object.prototype.hasOwnProperty.call(window,"ontouchend")) {
		this.bTouchAvailable = true;
		evPress = "touchend";
		evDragStart = "touchstart";
		evDragMove = "touchmove";
		evDragEnd = "touchend";
	}
	this.button1.addEventListener(evPress,function() {
		_gthis.onButtonPress(_gthis.button1.value);
	});
	this.button2.addEventListener(evPress,function() {
		_gthis.onButtonPress(_gthis.button2.value);
	});
	this.button3.addEventListener(evPress,function() {
		_gthis.onButtonPress(_gthis.button3.value);
	});
	this.divTitle.addEventListener(evDragStart,$bind(this,this.startDrag));
	this.divBG.addEventListener(evDragMove,$bind(this,this.moveDrag));
	this.divBG.addEventListener(evDragEnd,$bind(this,this.endDrag));
};
MnDialog.prototype = {
	setTitle: function(text) {
		if(text != null) {
			this.divTitle.textContent = text;
		}
	}
	,setBody: function(text) {
		if(text != null) {
			this.divBody.textContent = text;
		}
	}
	,setBodyHTML: function(htmlText) {
		if(htmlText != null) {
			this.divBody.innerHTML = htmlText;
		}
	}
	,setColor: function(colorBase,colorTitle,colorTitleText,colorButton) {
		if(colorBase != null && colorBase != "") {
			this.colorBase = colorBase;
		}
		if(colorTitle != null && colorTitle != "") {
			this.colorTitle = colorTitle;
		}
		if(colorTitleText != null && colorTitleText != "") {
			this.colorTitleText = colorTitleText;
		}
		if(colorButton != null && colorButton != "") {
			this.colorButton = colorButton;
		}
		this.outputCSS();
	}
	,outputCSS: function($delete) {
		if($delete == null) {
			$delete = true;
		}
		var oCSS = window.document.getElementById(this.cssPrefix);
		if(oCSS != null) {
			if(!$delete) {
				return;
			}
			window.document.head.removeChild(oCSS);
		}
		var cssPrefix = this.cssPrefix + "_";
		var css = "\n." + cssPrefix + "bg{\n    display: none;\n    background-color: rgba(0, 0, 0, 0.2);\n    position: fixed;\n    left: 0;\n    top: 0;\n    width: 100%;\n    height: 100%;\n}\n." + cssPrefix + "base{\n    position: absolute;\n    left: 50%;\n    top: 50%;\n    width: " + this.width + "px;\n    min-height: " + this.height + "px;\n    transform: translate(-50%, -50%);\n    background-color: " + this.colorBase + ";\n    border: solid 2px " + this.colorTitle + ";\n    border-radius: 4px;\n    text-align: left;\n    font-size: 0.8rem;\n}\n." + cssPrefix + "title{\n    background-color: " + this.colorTitle + ";\n    color: " + this.colorTitleText + ";\n    padding: 3px;\n    cursor: pointer;\n    user-select: none;\n    -ms-user-select: none;\n    -moz-user-select: none;\n    -webkit-user-select: none;\n}\n." + cssPrefix + "body{\n    padding: 3px;\n    height: " + (this.height - 60) + "px;\n    max-height: " + this.maxBodyHeight + "px;\n    overflow-y: auto;\n}\n." + cssPrefix + "buttons{\n    text-align: center;\n    padding: 3px;\n}\n." + cssPrefix + "button{\n    border-style: none;\n    color: " + this.colorTitleText + ";\n    background-color: " + this.colorTitle + ";\n    cursor: pointer;\n    border-radius: 4px;\n    min-width: 60px;\n    min-height: 20px;\n    margin: 4px;\n    padding-left: 4px;\n    padding-right: 4px;\n}\n." + cssPrefix + "button:hover{\n    background-color: " + this.colorButton + ";\n}";
		var style = window.document.createElement("style");
		style.id = this.cssPrefix;
		style.appendChild(window.document.createTextNode(css));
		window.document.head.appendChild(style);
		oCSS = window.document.getElementById(this.cssPrefix);
	}
	,setButtonType: function(btType,lang) {
		if(lang == null) {
			lang = "en";
		}
		if(btType == null) {
			btType = "OK";
		}
		if(lang == null) {
			lang = "en";
		}
		this.btLang = lang;
		var caption;
		switch(lang) {
		case "fr":
			caption = { ok : "OK", cancel : "Annuler", yes : "Oui", no : "Non"};
			break;
		case "jp":
			caption = { ok : "OK", cancel : "キャンセル", yes : "はい", no : "いいえ"};
			break;
		default:
			caption = { ok : "OK", cancel : "Cancel", yes : "Yes", no : "No"};
		}
		this.button2.style.display = "none";
		this.button3.style.display = "none";
		this.btType = btType;
		switch(btType) {
		case "None":
			this.button1.style.display = "none";
			this.button2.style.display = "none";
			this.button3.style.display = "none";
			break;
		case "OK":
			this.button1.textContent = caption.ok;
			this.button1.value = "OK";
			break;
		case "OKCancel":
			this.button1.textContent = caption.ok;
			this.button1.value = "OK";
			this.button2.style.display = "";
			this.button2.textContent = caption.cancel;
			this.button2.value = "Cancel";
			break;
		case "YesNo":
			this.button1.textContent = caption.yes;
			this.button1.value = "Yes";
			this.button2.style.display = "";
			this.button2.textContent = caption.no;
			this.button2.value = "No";
			break;
		case "YesNoCancel":
			this.button1.textContent = caption.yes;
			this.button1.value = "Yes";
			this.button2.style.display = "";
			this.button2.textContent = caption.no;
			this.button2.value = "No";
			this.button3.style.display = "";
			this.button3.textContent = caption.cancel;
			this.button3.value = "Cancel";
			break;
		}
	}
	,setButtonCaption: function(bt1Caption,bt2Caption,bt3Caption) {
		if(bt1Caption != null) {
			this.button1.textContent = bt1Caption;
		}
		if(bt2Caption != null) {
			this.button2.textContent = bt2Caption;
		}
		if(bt3Caption != null) {
			this.button3.textContent = bt3Caption;
		}
	}
	,setButtonCallback: function(cbFunc) {
		this.cbButton = cbFunc;
	}
	,enableKeyup: function(bFlag) {
		this.keyupEnabled = bFlag;
	}
	,cbKeyup: function(ev) {
		if(this.divBG.style.display == "none") {
			return;
		}
		switch(ev.key) {
		case "Enter":
			if(this.btType == "OK" || this.btType == "OKCancel") {
				this.hide();
				this.onButtonPress("OK");
			}
			break;
		case "Esc":case "Escape":
			if(this.btType == "OKCancel" || this.btType == "YesNoCancel") {
				this.hide();
				this.onButtonPress("Cancel");
			}
			break;
		}
	}
	,setButtonFocus: function(btNumber) {
		if(btNumber == null) {
			btNumber = "";
		}
		if(btNumber != "") {
			this.btFocused = btNumber;
		} else {
			btNumber = this.btFocused;
		}
		switch(btNumber) {
		case "button1":
			this.button1.focus();
			break;
		case "button2":
			this.button2.focus();
			break;
		case "button3":
			this.button3.focus();
			break;
		default:
			this.btFocused = "none";
			this.button1.blur();
			this.button2.blur();
			this.button3.blur();
		}
	}
	,show: function(iFixedLeft,iFixedTop) {
		if(iFixedLeft == null) {
			this.divBase.style.left = "";
		} else {
			this.divBase.style.left = iFixedLeft + "px";
		}
		if(iFixedTop == null) {
			this.divBase.style.top = "";
		} else {
			this.divBase.style.top = iFixedTop + "px";
		}
		if(this.keyupEnabled) {
			window.addEventListener("keyup",$bind(this,this.cbKeyup));
		}
		this.divBG.style.display = "block";
		this.setButtonFocus();
	}
	,hide: function() {
		this.divBG.style.display = "none";
		if(this.keyupEnabled) {
			window.removeEventListener("keyup",$bind(this,this.cbKeyup));
		}
	}
	,onButtonPress: function(button_value) {
		this.hide();
		if(this.cbButton != null) {
			this.cbButton.call(this,button_value);
		}
	}
	,startDrag: function(ev) {
		this.bDragging = true;
		var evt = ev;
		if(this.bTouchAvailable) {
			evt = ev.changedTouches[0];
		}
		this.iX = evt.pageX;
		this.iY = evt.pageY;
	}
	,moveDrag: function(ev) {
		ev.preventDefault();
		if(!this.bDragging) {
			return;
		}
		var evt = ev;
		if(this.bTouchAvailable) {
			evt = ev.changedTouches[0];
		}
		this.divBase.style.left = this.divBase.offsetLeft + evt.pageX - this.iX + "px";
		this.divBase.style.top = this.divBase.offsetTop + evt.pageY - this.iY + "px";
		this.iX = evt.pageX;
		this.iY = evt.pageY;
	}
	,endDrag: function() {
		this.bDragging = false;
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
