// Generated by Haxe 4.0.3
(function ($hx_exports, $global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
Math.__name__ = true;
var MnDialog = $hx_exports["MnDialog"] = function(width,height,id,cssPrefix) {
	if(height == null) {
		height = 150;
	}
	if(width == null) {
		width = 250;
	}
	this.id = "";
	this.colorBase = "#eeeeff";
	this.colorButton = "#6666ff";
	this.colorTitleText = "#ffffff";
	this.colorTitle = "#9999ff";
	var _gthis = this;
	if(id != null) {
		this.id = id;
	}
	if(cssPrefix != null) {
		this.cssPrefix = cssPrefix;
	} else {
		this.cssPrefix = "mndlg_" + new Date().getTime();
	}
	this.width = width;
	this.height = height;
	this.outputCSS(false);
	cssPrefix = this.cssPrefix + "_";
	this.divBG = window.document.createElement("div");
	this.divBG.className = cssPrefix + "bg";
	window.document.body.appendChild(this.divBG);
	this.divBase = window.document.createElement("div");
	this.divBase.className = cssPrefix + "base";
	if(this.id != "") {
		this.divBase.id = this.id;
	}
	this.divBG.appendChild(this.divBase);
	this.divTitle = window.document.createElement("div");
	this.divTitle.className = cssPrefix + "title";
	this.divTitle.textContent = "Title";
	this.divBase.appendChild(this.divTitle);
	this.divBody = window.document.createElement("div");
	this.divBody.innerHTML = "";
	this.divBody.className = cssPrefix + "body";
	this.divBase.appendChild(this.divBody);
	this.divButtons = window.document.createElement("div");
	this.divButtons.className = cssPrefix + "buttons";
	this.divBase.appendChild(this.divButtons);
	this.button1 = window.document.createElement("button");
	this.button1.textContent = "OK";
	this.button1.value = "OK";
	this.button1.className = cssPrefix + "button";
	this.button1.name = "button1";
	this.divButtons.appendChild(this.button1);
	this.button2 = window.document.createElement("button");
	this.button2.textContent = "Cancel";
	this.button2.value = "Cancel";
	this.button2.className = cssPrefix + "button";
	this.button2.name = "button2";
	this.divButtons.appendChild(this.button2);
	this.button3 = window.document.createElement("button");
	this.button3.textContent = "NO!";
	this.button3.value = "No";
	this.button3.className = cssPrefix + "button";
	this.button3.name = "button3";
	this.divButtons.appendChild(this.button3);
	var evAction = "click";
	if(Object.prototype.hasOwnProperty.call(window,"ontouchend")) {
		evAction = "touchend";
	}
	this.button1.addEventListener(evAction,function() {
		_gthis.onButtonPress(_gthis.button1);
	});
	this.button2.addEventListener(evAction,function() {
		_gthis.onButtonPress(_gthis.button2);
	});
	this.button3.addEventListener(evAction,function() {
		_gthis.onButtonPress(_gthis.button3);
	});
};
MnDialog.__name__ = true;
MnDialog.prototype = {
	setTitle: function(text) {
		if(text != null) {
			this.divTitle.textContent = text;
		}
	}
	,setColor: function(colorBase,colorTitle,colorTitleText,colorButton) {
		if(colorBase != null && colorBase != "") {
			this.colorBase = colorBase;
		}
		if(colorTitle != null && colorTitle != "") {
			this.colorTitle = colorTitle;
		}
		if(colorTitleText != null && colorTitleText != "") {
			this.colorTitleText = colorTitleText;
		}
		if(colorButton != null && colorButton != "") {
			this.colorButton = colorButton;
		}
		this.outputCSS();
	}
	,outputCSS: function($delete) {
		if($delete == null) {
			$delete = true;
		}
		var oCSS = window.document.getElementById(this.cssPrefix);
		haxe_Log.trace(oCSS,{ fileName : "MnDialog.hx", lineNumber : 136, className : "MnDialog", methodName : "outputCSS"});
		if(oCSS != null) {
			if(!$delete) {
				haxe_Log.trace("Canceled deletion of css: ",{ fileName : "MnDialog.hx", lineNumber : 139, className : "MnDialog", methodName : "outputCSS", customParams : [this.cssPrefix]});
				return;
			}
			window.document.head.removeChild(oCSS);
		}
		var cssPrefix = this.cssPrefix + "_";
		var css = "." + cssPrefix + "bg{\n    display: none;\n    background-color: rgba(0, 0, 0, 0.2);\n    position: fixed;\n    left: 0;\n    top: 0;\n    width: 100%;\n    height: 100%;\n}\n." + cssPrefix + "base{\n    position: absolute;\n    left: 50%;\n    top: 50%;\n    width: " + this.width + "px;\n    min-height: " + this.height + "px;\n    transform: translate(-50%, -50%);\n    background-color: " + this.colorBase + ";\n    border: solid 2px " + this.colorTitle + ";\n    border-radius: 4px;\n}\n." + cssPrefix + "title{\n    background-color: " + this.colorTitle + ";\n    color: " + this.colorTitleText + ";\n    padding: 3px;\n}\n." + cssPrefix + "body{\n    padding: 3px;\n    height: " + (this.height - 60) + "px;\n}\n." + cssPrefix + "buttons{\n    text-align: center;\n    padding: 3px;\n}\n." + cssPrefix + "button{\n    border-style: none;\n    color: " + this.colorTitleText + ";\n    background-color: " + this.colorTitle + ";\n    cursor: pointer;\n    border-radius: 4px;\n    min-width: 40px;\n}\n." + cssPrefix + "button:hover{\n    background-color: " + this.colorButton + ";\n}";
		var style = window.document.createElement("style");
		style.id = this.cssPrefix;
		style.appendChild(window.document.createTextNode(css));
		window.document.head.appendChild(style);
		oCSS = window.document.getElementById(this.cssPrefix);
		haxe_Log.trace(oCSS,{ fileName : "MnDialog.hx", lineNumber : 250, className : "MnDialog", methodName : "outputCSS"});
	}
	,setButtonType: function(btType,lang) {
		haxe_Log.trace(btType,{ fileName : "MnDialog.hx", lineNumber : 254, className : "MnDialog", methodName : "setButtonType"});
		this.button2.style.display = "none";
		this.button3.style.display = "none";
		switch(btType) {
		case "OK":
			this.button1.textContent = "OK";
			this.button1.value = "OK";
			break;
		case "OKCancel":
			this.button1.textContent = "OK";
			this.button1.value = "OK";
			this.button2.style.display = "";
			this.button2.textContent = "キャンセル";
			this.button2.value = "Cancel";
			break;
		case "YesNo":
			this.button1.textContent = "はい";
			this.button1.value = "Yes";
			this.button2.style.display = "";
			this.button2.textContent = "いいえ";
			this.button2.value = "No";
			break;
		case "YesNoCancel":
			this.button1.textContent = "はい";
			this.button1.value = "Yes";
			this.button2.style.display = "";
			this.button2.textContent = "いいえ";
			this.button2.value = "No";
			this.button3.style.display = "";
			this.button3.textContent = "キャンセル";
			this.button3.value = "Cancel";
			break;
		}
	}
	,setButtonCallback: function(cbFunc) {
		this.cbButton = cbFunc;
	}
	,show: function() {
		this.divBG.style.display = "block";
	}
	,onButtonPress: function(button) {
		this.divBG.style.display = "none";
		if(this.cbButton != null) {
			this.cbButton.call(this,button.value);
		}
	}
	,onButtonPress_1: function(event) {
		this.divBG.style.display = "none";
		if(this.cbButton != null) {
			this.cbButton.call(this,event.target);
		}
	}
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var haxe_Log = function() { };
haxe_Log.__name__ = true;
haxe_Log.formatOutput = function(v,infos) {
	var str = Std.string(v);
	if(infos == null) {
		return str;
	}
	var pstr = infos.fileName + ":" + infos.lineNumber;
	if(infos.customParams != null) {
		var _g = 0;
		var _g1 = infos.customParams;
		while(_g < _g1.length) {
			var v1 = _g1[_g];
			++_g;
			str += ", " + Std.string(v1);
		}
	}
	return pstr + ": " + str;
};
haxe_Log.trace = function(v,infos) {
	var str = haxe_Log.formatOutput(v,infos);
	if(typeof(console) != "undefined" && console.log != null) {
		console.log(str);
	}
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = o.length;
			while(_g3 < _g11) {
				var i = _g3++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = true;
Array.__name__ = true;
Date.__name__ = "Date";
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, {});
